### ISSUE TITLE
OpenFisca-Israel - openfisca setup

### ISSUE THREAD

**Issue by verbman** [ServiceInnovationLab/Piccolo#1]
Assist Israel as required to setup OpenFisca-Israel project so that later in the project we can create the actual calculation engine

- [x] git repo, and user permissions
- [x] Open fisca country template
- [x] server to host (heroku)
- [x] continuous deployment (circle ci)
- [x] DNS entry

**Comment by verbman** [comment]
Let's proceed with this process and set the repo's up (for now) in the Service Innovation Lab github space.

**Comment by dlouise64** [comment]
@Br3nda @verbman I added the domain in heroku

domain: openfisca-israel.services.govt.nz
dns target: openfisca-israel.services.govt.nz.herokudns.com

obviously its not resolving, where do I get subdomains for govt.nz?
