### ISSUE TITLE
OpenFisca-Israel rules coding

### ISSUE THREAD

**Issue by verbman** [ServiceInnovationLab/Piccolo#10]
Coding of israel rules into the OpenFisca-Israel instance

needs #1
needs #4

**Comment by CharlotteHinton** [comment]
Acceptance Criteria 

 - Implement Straw Man (it might not be correct, it's something to point at)

**Comment by CharlotteHinton** [comment]
@dlouise64 Can you drop the rules on here for Brenda - thanks :)

**Comment by Br3nda** [comment]
Rules here https://github.com/ServiceInnovationLab/Piccolo/issues/4#issuecomment-429688879
