### ISSUE TITLE
Addition of 'demo' label

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/Piccolo#142]
As the Lab
We know that Piccolo is only a demo, but when showcased on the D7 website others might not, so we need to communicate with them that it is.

A / C
 - Add some sort of 'demo' badge to the website (demonstration only)

Story is for both design and development.

**Comment by dlouise64** [comment]
@ssibbehh just wondering where I should put the label

**Comment by dlouise64** [comment]
closes #195
