### ISSUE TITLE
Eligibility showing "year 0"

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/Piccolo#143]
When I entered an age of 69 and 0 for all other inputs, it returns a value that I'm eligible for a pension in NZ at the age of 0

**Comment by CharlotteHinton** [comment]
[Uploading Screen Shot 2018-10-26 at 7.50.26 AM.png...]
[Uploading Screen Shot 2018-10-26 at 7.50.14 AM.png...]
[Uploading Screen Shot 2018-10-26 at 7.50.02 AM.png...]

**Comment by CharlotteHinton** [comment]
[Uploading Screen Shot 2018-10-26 at 7.50.26 AM.png...]
[Uploading Screen Shot 2018-10-26 at 7.50.14 AM.png...]
[Uploading Screen Shot 2018-10-26 at 7.50.02 AM.png...]

**Comment by CharlotteHinton** [comment]
![Screen Shot 2018-10-26 at 7.50.26 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc3adfaa62f720013153b36/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f56b7191a37ff1172b4f5d595edd3c4a4356bcbbd671f3e57862804e0ebf833c5872933414feea8249b801ba24884884b6eed944d2f42f67b6d5db1063474f4dcbed5727a29941c95df24be54456a2163f62e1742431.png)
![Screen Shot 2018-10-26 at 7.50.14 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc3adfaa62f720013153b36/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f56b7191a37ff1172b4f5e5b5edd3c4a4356bcbbd671f3e57862804e0ebf833c5872933414feea8249b801ba24884884b6eed944d2f42f67b6d5db1063474f4dcbed5727a19041c95df24be54456a2163f62e3732431.png)
![Screen Shot 2018-10-26 at 7.50.02 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc3adfaa62f720013153b36/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f56b7191a37ff1172b4f5f5d5edd3c4a4356bcbbd671f3e57862804e0ebf833c5872933414feea8249b801ba24884884b6eed944d2f42f67b6d5db1063474f4dcbed5727a19e41c95df24be54456a2163f62e0742431.png)

**Comment by dlouise64** [comment]
fixed in #139
