### ISSUE TITLE
Rules for Uruguay

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/Piccolo#176]
Is the calculation from age 60, as a woman who has worked 30 years
and aged 70 for a woman that was worked less than 30 years (this is how it looks to be calculating this). This is accurate? As there doesn't seem to be calculation for an age for 62. 

It appears that the calculation is always come back from 60, not 62 in the app.

Is this dependent on #146?

**Comment by Br3nda** [comment]
It's from age 70 if worked 15 years

**Comment by dlouise64** [comment]
@Br3nda thanks brenda!
