### ISSUE TITLE
OpenFisca-Uruguay - openfisca setup

### ISSUE THREAD

**Issue by verbman** [ServiceInnovationLab/Piccolo#2]
Assist Uruquay as required to setup OpenFisca-Uruguay project

- [x] git repo, and user permissions
- [x] Open fisca country template
- [x] server to host (heroku)
- [x] continuous deployment (circle ci)
- [x] DNS entry

**Comment by verbman** [comment]
Let's proceed with this process and set the repo's up (for now) in the Service Innovation Lab github space.

**Comment by dlouise64** [comment]
@Br3nda @verbman please check in heroku too
