### ISSUE TITLE
Determine Uruguay Pension Questions

### ISSUE THREAD

**Issue by verbman** [ServiceInnovationLab/Piccolo#3]
Determine parameters needed by Uruguay legislation to determine eligibility  so that we can enter the logic into the equivalent OpenFisca instance.

**Comment by dlouise64** [comment]
Have created a questions doc here: https://docs.google.com/document/d/1kkt0fhLo7kIpV3QOVW_-yZN11d01Gq98kJN0hrjtJSg/edit
