### ISSUE TITLE
Build front-end UI

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/Piccolo#67]
Elements
- [x] Headings
- [x] Paragraphs
- [x] Input Textfield (incl. focus)
- [x] Button
- [x] Sections (dark, light, grey)
- [x] Main
- [x] Container
- [x] List - stripped
- [x] Column (grid)
- [x] Icons

Components
- [x] Page Header
- [x] Section Header
- [x] Field
- [x] Creative Commons
- [x] Adlib
- [x] Circle Icon
- [x] Footer

**Comment by CharlotteHinton** [comment]
Size is related to what's left to do (only three done at time of sizing)
