### ISSUE TITLE
Development: Querying OpenFisca NZ

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/Piccolo#72]
As a developer
I want to query OpenFisca NZ
For it to return an end result

A / C
 - Three answers appear on the screen and they are correct
- Work out what parameters to send to each country

**Comment by CharlotteHinton** [comment]
@dlouise64 Can we check in on this when you are online please - just to get a status update. Thanks

**Comment by CharlotteHinton** [comment]
Notes. Rules are in for NZ already

**Comment by dlouise64** [comment]
@CharlotteHinton @Br3nda NZ rules are missing variables for pension eligibility age. This needs to be done

**Comment by Br3nda** [comment]
I'm adding `super___eligibility_age` to openfisca-aotearoa now

**Comment by Br3nda** [comment]
i've added the new variable in this PR https://github.com/ServiceInnovationLab/openfisca-aotearoa/pull/97
