### ISSUE TITLE
Development: Building MadLib blurb

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/Piccolo#75]
As a user
I would like to see my results in an easy to read sentence.

A / C
 - Content is correct
 - Content should update as I enter values into the form
 - Content should match design

needs #80
needs #138

**Comment by CharlotteHinton** [comment]
@Br3nda @dlouise64 to catch-up on children

**Comment by dlouise64** [comment]
With Children
![Screen Shot 2018-10-25 at 9.09.43 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5d4e54c8f9d70012f9078a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f66b7191a371f112224f5b5c5edd3c4a4356bcbbd671f3e57862804e0ebf833c5872933414feea8249b801ba24884884b6eed944d2f42f67b6d5db1063474f4dcbed5727a19141c95df24be54c54ac123161e7712431.png)

No Children
![Screen Shot 2018-10-25 at 9.09.51 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5d4e54c8f9d70012f9078a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f66b7191a371f112224f5a5e5edd3c4a4356bcbbd671f3e57862804e0ebf833c5872933414feea8249b801ba24884884b6eed944d2f42f67b6d5db1063474f4dcbed5727a19e41c95df24be54c54ac173260e47e2431.png)
