### ISSUE TITLE
Design: Eligible explanations UR

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/Piccolo#77]
As a user
I want to see what age I will be eligible and an explanation of the criteria used to reached this conclusion.

A / C
 - Should have all of the determining variables written for UR

Assets:
Review the information that has been provided to ensure there's a match
https://drive.google.com/drive/folders/11mdH4DJ_uE1KQLu4P6PWxQlk2TSDjt7Q

**Comment by dlouise64** [comment]
@CharlotteHinton @Br3nda @ssibbehh  I have added the content for this in #147
