### ISSUE TITLE
Development: Make form functional

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/Piccolo#80]
As a developer
I need to make sure the form functions
So that it's useable.

Acceptance Criteria: 
 - When a value is typed the MadLib should show a response
 - The values you've entered are sent to NZ's OpenFisca to query
 - The values you've entered are sent to IL's OpenFisca to query
 - The results (age you can retire) is shown on the page

needs #67
needs #70
needs #72
needs #74

**Comment by dlouise64** [comment]
@Br3nda Am blocked on NZ rules but have put placeholder in place
