### ISSUE TITLE
OpenFisca-Uruguay rules coding

### ISSUE THREAD

**Issue by verbman** [ServiceInnovationLab/Piccolo#9]
Coding of Uruguay rules into the OpenFisca-Uruguay Instance

needs #2
needs #3

**Comment by CharlotteHinton** [comment]
@dlouise64 and @Br3nda to pair on this story to get the bones of the structure in place.

**Comment by CharlotteHinton** [comment]
@Br3nda - we've got the rule set from Uruguay now, I've added them into this folder. I'll set-up a new ticket to bring these in. This is an FYI 

https://drive.google.com/drive/folders/11mdH4DJ_uE1KQLu4P6PWxQlk2TSDjt7Q
